# Import

In [2]:
import pandas as pd
import sys
import re

import urllib.request


from pathlib import Path
sys.path.append("../..")

from file_management import check_save_file, get_files_dir

# Resolve project directories
_, INPUT_DIR, OUTPUT_DIR = get_files_dir()


from parse_LASER import get_tags

# Files

Path were the htmls were downloaded: 'https://bitbucket.org/jdwinkler/laser_release/src/master/database_store/'

## Input

In [3]:
LASER_FILES = INPUT_DIR / "LASER"
LASER_FILES.mkdir(parents=True, exist_ok=True)

LASER_WEBFILES = INPUT_DIR /"LASER"/"LASER_webfiles"

In [4]:
with open(LASER_WEBFILES /"2014.html", "r", encoding='latin') as f:
    laser_2014= f.read()
with open(LASER_WEBFILES /"2015.html", "r", encoding='latin') as f:
    laser_2015= f.read()

In [5]:
papers_2014 = re.findall(r"Record.{1,30}\.txt", laser_2014)
papers_2014 = set(papers_2014)
print(len(papers_2014))

papers_2015 = re.findall(r"Record.{1,30}\.txt", laser_2015)
papers_2015 = set(papers_2015)
print(len(papers_2015))

313
143

In [6]:
papers_sets = {"2014":list(papers_2014), "2015":list(papers_2015)}

In [7]:
url_ontology = (
    "https://bitbucket.org/jdwinkler/laser_release/raw/"
    "f6ce080a8993ee259c4914ce92f83b1f966bab2d/"
    "inputs/Product%20Ontology.txt"
)

database_url = (
    "https://bitbucket.org/jdwinkler/laser_release/raw/"
    "f6ce080a8993ee259c4914ce92f83b1f966bab2d/"
    "database_store/")

## Output

In [8]:
OUTPUT_FILE_ONTOLOGY = "LASER_product_ontology.txt"
OUTPUT_FILE_TAGS = "LASER_TAGS.json"
laser_ontology_file = LASER_FILES / OUTPUT_FILE_ONTOLOGY

# Download LASER Ontology

In [9]:
if not laser_ontology_file.exists():
    print("Downloading LASER_product_ontology.txt ...")
    urllib.request.urlretrieve(url_ontology, laser_ontology_file)
else:
    print("LASER_product_ontology.txt already exists.")

LASER_product_ontology.txt already exists.

In [10]:
LASER_ontology = pd.read_csv(laser_ontology_file, sep='\t')

In [11]:
LASER_ontology.head()

            Product   Intended usage product class
0   (2S)-NARINGENIN  pharmaceuticals      chalcone
1  (2S)-PINOCEMBRIN   food additives     phenolics
2   1_2-PROPANEDIOL         polymers         diols
3   1_3-PROPANEDIOL         polymers         diols
4    1_4-BUTANEDIOL         polymers         diols

# Get LASER tags

In [32]:
url_ontology = (
    "https://bitbucket.org/jdwinkler/laser_release/raw/"
    "f6ce080a8993ee259c4914ce92f83b1f966bab2d/"
    "inputs/Product%20Ontology.txt"
)

database_url = (
    "https://bitbucket.org/jdwinkler/laser_release/raw/"
    "f6ce080a8993ee259c4914ce92f83b1f966bab2d/"
    "database_store/")

In [33]:
full_tags = get_tags(papers_sets, database_url)

Try again  <http.client.HTTPResponse object at 0x10d7d7220>

In [40]:
full_tags

,Counts,Full_list,Set
0,2176,Tags,Mutant5.Mutation7.GeneNickname
1,2176,DOI,Mutant5.Mutation4.GeneMutation.plasmid
2,2176,SubmitterName,Mutant1.Mutation30.GeneEffect
3,2176,Title,Mutant6.Mutation1.GeneMutation.terminated
4,2176,project_score,Mutant1.Mutation14.GeneMutation.plasmid
...,...,...,...
2171,2176,Mutant1.Mutation4.GeneMutation.rbs_tuned,Mutant7.Mutation3.GeneMutation
2172,2176,Mutant1.Mutation8.GeneMutation.rbs_tuned,Mutant12.Mutation3.GeneOriginal
2173,2176,Mutant6.Mutation1.GeneMutation.integrated,Mutant5.Mutation3.GeneSource
2174,2176,Mutant4.Mutation6.GeneMutation.plasmid,Mutant12.Mutation1.GeneEffect
2175,2176,Mutant4.Mutation6.GeneMutation.aa_snps,Mutant4.FinalYield

In [38]:
full_tags = pd.DataFrame.from_dict(full_tags)

In [47]:
check_save_file(
    full_tags,
    OUTPUT_FILE_TAGS,
    "LASER",
    input_dir=True
)

Saved file in: /Users/elisamarquez/Documents/PhD/Utimo/ELISER-StrainDesignDB/files/Input/LASER/LASER_TAGS.json